#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx start
