#!/usr/bin/env bash
#  A Script that configures a new Ubuntu machine to Perform a 301-redirection
sudo apt-get update -y
# installs the Nginx web server.
sudo apt-get install  nginx -y

# sets the content of the index.html file to "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure a new server block for 301 redirection
old_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 301;"
sudo sed -i "s/server_name _;/$old_string/" /etc/nginx/sites-enabled/default

# Test Nginx configuration and reload
sudo nginx -t
sudo service nginx start
