#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# +    Listens on port 80.
# +    Returns a page containing "Hello World!" when queried
# ++    at the root with a curl GET request.

# updates the package lists for available software packages.
apt-get update
# installs the Nginx web server.
apt-get install -y nginx

# Creates the /etc/nginx/html director.
# This will serve as the document root directory for Nginx.
mkdir /etc/nginx/html
# creates an empty index.html file inside the /etc/nginx/html directory.
touch /etc/nginx/html/index.html
# sets the content of the index.html file to "Hello World!"
echo "Hello World!" > /etc/nginx/html/index.html
# Sets Nginx to listen on port 80 on ipv4/6 and sets root to /etc/nginx/html
# directory where Nginx will look for files, defines the default index files
printf %s "server {
    listen      80;
    listen      [::]:80 default_server;
    root        /etc/nginx/html;
    index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Configure a new server block for redirection
# sudo with | reads from stdin to stdout to 'redirect' file
echo "server {
    listen 80;
    listen [::]:80;

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
# the above block of config made to path,/redirect_me move u this youtube link.
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/redirect

# Enable the new site configuration
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Test Nginx configuration and reload
sudo nginx -t
sudo service nginx reload
