#!/usr/bin/env bash
# Script that installs and configures an Nginx server
# configure nginx to redirect /redirect_me to another page
# displays a custom error 404 page

sudo apt-get update -y
# installs the Nginx web server.
sudo apt-get install -y nginx

# sets the content of the index.html file to "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure a new server block for 301 redirection
old_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 301;"
sudo sed -i "s/server_name _;/$old_string/" /etc/nginx/sites-enabled/default

# Using sed to configure an error page
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Test Nginx configuration and reload
sudo nginx -t
sudo service nginx start
