#!/usr/bin/env bash
# Script that replicates Nginx web-01 config in web-02 server.
# config includes display of Html custom page
# redirect (ip/redirect_me) to another page
# displays a custom error 404 page
# custom HTTP response header

sudo apt-get update -y
# installs the Nginx web server.
sudo apt-get install -y nginx

# sets the content of the index.html file to "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure a new server block for 301 redirection
old_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$old_string/" /etc/nginx/sites-enabled/default

# Using sed to configure an error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# custom HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test Nginx configuration and reload
sudo nginx -t
sudo service nginx reload
