#!/usr/bin/env bash
# Script that install and configure HAproxy on lb-01 server
# Distribute requests using a roundrobin algorithm
# config includes that HAproxy be managed via an init script
# servers are configured with the right hostnames: [STUDENT_ID]-web-01 or02

sudo apt-get update -y
sudo apt-get install -y haproxy

# Edits the /etc/haproxy/haproxy.cfg
Haproxy_config=\
"
frontend daraja_frontend
        bind *:80
        mode http
	default_backend daraja_backend
backend daraja_backend
        balance roundrobin
        server 176572-web-01 100.25.162.179:80 check
        server 176572-web-02 54.161.253.7:80 check
"
echo "$Haproxy_config" >> /etc/haproxy/haproxy.cfg

# Enable haproxy to be started by init script
echo 'ENABLED=1'  sudo tee -a /etc/default/haproxy


# Test Haproxy configuration and start
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service nginx start
