#!/usr/bin/env bash
#A bash script that  pings an IP address passed as an argument.

#Requirements:

#Accepts a string as an argument
#Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
#Ping the IP 5 times

if [ -z "$1" ]; then
	 echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else 

host="$1"
count=5

	for ((i=1; i<=count; i++)); do
		echo "ping $i"
		ping -c 5 "$host"
	done
fi
