#!/usr/bin/env bash
#A Bash script that displays the PID, along with the process name, of processes whose name contain the word bash. No use of ps
script_pid=$$
#gets the PID of the scipt
pgrep -l bash
