#!/usr/bin/env bash
#A Bash script that displays numbers from 1 to 100.

#Requirements:

#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number
#In a list format

n="FizzBuzz"
m="Fizz"
o="Buzz"
counter=1
while [ $counter -le 100 ]; do
	if [ $((counter%3)) -eq 0 ] && [ $((counter%5)) -eq 0 ]; then
		echo "$n"
	elif [ $((counter%3)) -eq 0 ]; then
		echo "$m"
	elif [ $((counter%5)) -eq 0 ]; then
		echo "$o"
	else
		echo "$counter"
	fi
	(( counter++))
done
