#!/usr/bin/env bash
#A Bash script that displays the content of the file /etc/passwd.

#Your script should only display:

#username
#user id
#Home directory path for the user. Use while loop

while IFS=: read -r username userid homedir; do
	echo "$username:$userid:$homedir"
done < "/etc/passwd"

