#!/usr/bin/env bash
#A Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.

#Requirement:

#Format: IP HTTP_CODE
#in a list format
#See example
#You must use awk
#You are not allowed to use while, for, until and cut

awk -F' ' '{print $1, $9}' apache-access.log
#awk scans through the text file containing input fields from $1 to $9 seperated by space as set by field seperator, F. Each of $1 to $9 stands for something.
