#!/usr/bin/env bash
#A Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line. Must use while and if loop.
n="Best School"
m="Hi"
i=0
while [ $i -le 9 ]; do
	if [ $i -eq 8 ]; then
		echo "$n"
		echo "$m"
	else
		echo "$n"
	fi
	((i++))
done
