#!/usr/bin/env bash
#A Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations using while, if, elif, else.
n="Best School"
m="bad luck"
o="good luck"
i=1
while [ $i -le 10 ]; do
        if [ $i -eq 4 ]; then
                echo "$m"
	elif [ $i -eq 8 ]; then
                echo "$o"
	else
		echo "$n"
        fi
        ((i++))
done
