#!/usr/bin/env bash
#A Bash script that displays numbers from 1 to 20 and:

#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration. Use while loop and case statment.

m="bad luck from China"
n="bad luck from Japan"
o="bad luck from Italy"

counter=1

while [ "$counter" -le 20 ];
do
	echo "$counter"
	case "$counter" in
		"4")
			echo "$m"
			;;
		"9")
			echo "$n"
			;;
		"17")
			echo "$o"
			;;
		*)
	esac

	((counter++))
done
