#!/usr/bin/env bash
# Configure Nginx to serve your page from route:/airbnb-onepage/

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/;
    }
}
